config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'

  resources :recipes do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :name, :rating, :comment, presence:true
  validates_length_of :comment, maximum:200

  RATING=[0,1,2,3,4,5]
  validates_inclusion_of :rating, in:RATING

  belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

    validates :name, :stuff, :duration, :prepare_mode, presence:true
    validates_length_of :stuff, maximum: 1000
    validates_length_of :stuff, maximum: 3000
    validates_numericality_of :calories, greater_than_or_equal_to:0, presence:true
    validates_format_of :poster, allow_blank:true,  with: /\w+\.(gif|jpeg|jpg|png)\z/i, message: "somente arquivos gif, jpeg, jpg ou png"
    
    KIND = %w(Carnes Aves Peixes Massas Saladas Doces)
    validates_inclusion_of :kind, in: KIND

    has_many :comments, dependent: :destroy

    def light?
        calories.blank? || calories < 100
    end

    def self.created_at
        where("created_at <= ?", Time.now).order("created_at desc")
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :set_recipe

    def index
        @comments = @recipe.comments
    end

    def new
        @comment = @recipe.comments.new
    end

    def create
        @comment = @recipe.comments.new(comment_params)
        if @comment.save
            redirect_to recipe_comments_path(@recipe), notice: "Avaliação enviada! Obrigada"
        else
            render :new
        end
    end

    private

        def comment_params
            params.require(:comment).permit(:name, :comment, :rating)
        end

        def set_recipe
            @recipe = Recipe.find(params[:recipe_id])
        end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.created_at
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe, notice:"Sua receita foi editada."
        else
            render :edit
        end
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe, notice:"Sua receita foi criada com sucesso."
        else
            render :new
        end
    end
    
    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_url, alert:"Receita excluída :("
    end

    private 
    def recipe_params
        params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Light (menos de 100 calorias)")
        else
            recipe.calories 
        end
    end

    def imagem(recipe)
        if recipe.poster.blank?
            image_tag('Produto-sem-imagem.png', size: "300x300")
        else
            image_tag(recipe.poster, size: "300x300")
        end
    end

end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment]) do |f| %>

    <%= render 'layouts/errors', object: @comment %>

    <p class="form-group">
        <%= f.label :Nome %> <br>
        <%= f.text_field :name, autofocus:true, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Estrelas %> <br>
        <%= f.select :rating, Comment::RATING, prompt:"Dê a sua nota", class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Comentário %> <br>
        <%= f.text_area :comment, placeholder:"Escreva um comentário", class:"form-control" %>
    </p>
    <p>
        <%= f.submit class:'btn btn-primary' %>
        <%= link_to "Cancelar", root_path, class:"btn btn-default" %>
    </p>

<% end %>

app/views/comments/index.html.erb
<div class="jumbotron container">
    <div class="comments-container container">
        <% if @recipe.comments.size > 0 %>
            <ul>
                <% @comments.each do |comment| %>
                <li>
                    <p class="lead">
                        <%= comment.name %> 
                        <small class="small_font_rating"> <br> <%= pluralize(comment.rating, "estrela", "estrelas") %> </small>
                        <small class="small_font"> - escrito há <%= time_ago_in_words(comment.created_at) %> </small>
                    </p>
                    <p class="display-4">"<%= comment.comment %>"</p>
                </li>
                <% end %>
            </ul>
        <% else %>
            <p class="text-center">
                Essa receita ainda não tem avaliações <br> &#128543
            </p>
        <% end %>
    </div>

    <button type="button" class="btn btn-outline-light" data-toggle="tooltip" data-placement="auto" title="ver receitas">
        <%= link_to image_tag('repo.svg', alt:'voltar a home'), recipes_path %>
    </button>

</div>

app/views/comments/new.html.erb
<div class="container">
    <div class="novo-comentario card">
        <div class="card-title">
            <h2> Nova avaliação </h2>
        </div>
        <div class="card-body">

        <%= render 'form' %>
            
        </div>
    </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>

    <div class="alert alert-secondary" role="alert">
        <ul>
            <%= object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
        <div class="container alert alert-success alert-dismissible fade show" role="alert">
            <strong>Pronto!</strong> <%= flash[:notice] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
<% elsif flash[:alert] %>
    <div class="container alert alert-dark alert-dismissible fade show" role="alert">
        <strong>Pronto!</strong> <%= flash[:alert] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <p class="text-muted">
            Love Cooking: seu livro de receitas virtual.
        </p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to image_tag('logo.png', alt:'Logo Love Cooking'), root_path, class:'navbar-brand' %>
  <p> love cooking </p>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/flash' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

    <%= render 'layouts/errors', object: @recipe %>

    <p class="form-group">
        <%= f.label :Nome %> <br>
        <%= f.text_field :name, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Ingredientes %> <br>
        <%= f.text_area :stuff, col:20, rows:5, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Tipo %> <br>
        <%= f.select :kind, Recipe::KIND, prompt:"Escolha uma opção", class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Calorias %> <br>
        <%= f.number_field :calories, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Porções %> <br>
        <%= f.text_field :portion, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Tempo_de_preparo %> <br>
        <%= f.time_select :duration, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Modo_de_preparo %> <br>
        <%= f.text_area :prepare_mode, col:20, rows:5, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Custo %> <br>
        <%= f.number_field :cost, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Poster %> <br>
        <%= f.number_field :poster, placeholder:".GIF, .JPEG, .PNG", class:"form-control" %>
    </p>
    <p>
        <%= f.submit class:"btn btn-primary" %>
        <%= link_to "Cancelar", root_path, class:"btn btn-light" %>
    </p>
<% end %>

app/views/recipes/edit.html.erb
<div class="form-new-recipe container">
    <div class="card">
        <div class="card-header">
            <h2>Editando a receita</h2>
        </div>
        <div class="card-body">
            <%= render 'form'%>
        </div>
    </div>
</div>

app/views/recipes/index.html.erb
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h2 class="main header"> 
                <p>No momento temos: <%= pluralize(@recipes.size, "Receita", "Receitas") %></p> <br>
                <small class="nova-receita text-lowercase font-weight-light">
                    <%= link_to "+ Nova receita", new_recipe_path %>
                </small>
            </h2>
        </div>
    </div>

    <div class="main container">
        <% @recipes.each do |recipe| %>
            <div class="recipe-card row">
                <div class="col-4">
                    <%= link_to imagem(recipe), recipe%>
                </div>
                <div class="recipe-content col-8">
                    <h5><%= link_to recipe.name , recipe %></h5>
                    <p>
                        <p> <%= truncate(recipe.stuff, length:150, separator:'') %> </p>
                        <h4> Calorias: </h4>
                        <p> <%= formata_caloria(recipe) %> </p>
                        <h4> Tempo de preparo: </h4>
                        <p> <%= recipe.duration.to_formatted_s(:time) %> </p>
                        <h4> Custo: </h4>
                        <p> <%= number_to_currency(recipe.cost) %> </p>
                    </p>
                </div>
            </div>
            <hr>
        <% end %>
    </div>        

</div>

app/views/recipes/new.html.erb
<div class="form-new-recipe container">
    <div class="card">
        <div class="card-header">
            <h2>Criando uma nova receita</h2>
        </div>
        <div class="card-body">
            <%= render 'form'%>
        </div>
    </div>
</div>

app/views/recipes/show.html.erb
<div class="show-container container">

    <header>
        <h1> <%= @recipe.name %> </h1>
        <%= imagem(@recipe) %>
    </header>

    <h2>Tipo</h2>
    <p> <%= @recipe.kind %> </p>

    <h2>Ingredientes</h2>
    <p> <%= @recipe.stuff %> </p>

    <h2>Calorias</h2>
    <p> <%= @recipe.calories %> </p>

    <h2>Tempo de preparo</h2>
    <p> <%= @recipe.duration.to_formatted_s(:time) %> </p>

    <h2>Porções</h2>
    <p> <%= pluralize(@recipe.portion, "porção", "porções") %> </p>

    <h3>Modo de preparo</h3>
    <p> <%= @recipe.prepare_mode %> </p>
    
    <h3>Custo</h3>
    <p> <%= number_to_currency(@recipe.cost) %> </p>

    <div class="avaliar">
        <h3>Avaliações</h3>
        <%= link_to pluralize(@recipe.comments.size, "avaliação", "avaliações"), recipe_comments_path(@recipe) %>
        <br>
        <%= link_to "Avaliar", new_recipe_comment_path(@recipe), class:'btn btn-primary' %>
    </div>

    <div class="buttons">

        <button type="button" class="btn btn-outline-light" data-toggle="tooltip" data-placement="auto" title="ver receitas">
            <%= link_to image_tag('repo.svg', alt:'voltar a home'), recipes_path %>
        </button>

        <button type="button" class="btn btn-outline-light" data-toggle="tooltip" data-placement="auto" title="editar">
            <%= link_to image_tag('pencil.svg', alt:'editar receita'), edit_recipe_path(@recipe) %>
        </button>

        <button type="button" class="btn btn-outline-light" data-toggle="tooltip" data-placement="auto" title="deletar">
            <%= link_to image_tag('trash.svg', alt:'deletar receita'), recipe_path(@recipe), method: :delete, data:{confirm: "Deseja mesmo deletar essa receita?"} %>
        </button>
    </div>

</div>